# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: appium iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - uses: actions/setup-node@v2
      with:
        node-version: '10.16.3'
    - run: |
            npm install -g appiumv1.22.3
            appium -v
            appium &>/dev/null &
    - name: Build with Maven
      run: mvn clean test -Dtest=CreateTaskTests#createTaskiOS
